"""add conversation title

Revision ID: 33e60afa7bda
Revises: c02e416f4f79
Create Date: 2026-07-23 16:18:29.412894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e60afa7bda'
down_revision: Union[str, Sequence[str], None] = 'c02e416f4f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            server_default="New Conversation",
        ),
    )
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
